"""Export a document and camera state to PNG or SVG without mutating application state."""

from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QRect, QSize
from PySide6.QtGui import QColor, QImage, QPainter, QPalette
from PySide6.QtSvg import QSvgGenerator

from pygeolab.model.document import Document
from pygeolab.rendering.renderer import Renderer
from pygeolab.rendering.viewport import Viewport


def _scaled_viewport(viewport: Viewport, scale: float) -> Viewport:
    if not 0.25 <= scale <= 8.0:
        raise ValueError("Le facteur de résolution doit être compris entre 0.25 et 8")
    return Viewport(
        center=viewport.center,
        scale=viewport.scale * scale,
        width=max(1, round(viewport.width * scale)),
        height=max(1, round(viewport.height * scale)),
    )


def export_png(
    path: str | Path,
    document: Document,
    viewport: Viewport,
    palette: QPalette,
    *,
    scale: float = 1.0,
    transparent: bool = False,
) -> Path:
    """Render the visible scene to a lossless PNG at a configurable resolution."""
    target = Path(path)
    if target.suffix.lower() != ".png":
        target = target.with_suffix(".png")
    export_viewport = _scaled_viewport(viewport, scale)
    image = QImage(
        export_viewport.width,
        export_viewport.height,
        QImage.Format.Format_ARGB32_Premultiplied,
    )
    image.fill(QColor(0, 0, 0, 0) if transparent else palette.window().color())
    painter = QPainter(image)
    try:
        Renderer().render(
            painter,
            document,
            export_viewport,
            palette,
            draw_background=not transparent,
        )
    finally:
        painter.end()
    target.parent.mkdir(parents=True, exist_ok=True)
    if not image.save(str(target), b"PNG"):
        raise ValueError(f"Impossible d'exporter l'image PNG : {target}")
    return target


def export_svg(
    path: str | Path,
    document: Document,
    viewport: Viewport,
    palette: QPalette,
    *,
    scale: float = 1.0,
    transparent: bool = False,
) -> Path:
    """Render the visible scene as scalable vector graphics with vector geometry and labels."""
    target = Path(path)
    if target.suffix.lower() != ".svg":
        target = target.with_suffix(".svg")
    export_viewport = _scaled_viewport(viewport, scale)
    target.parent.mkdir(parents=True, exist_ok=True)
    generator = QSvgGenerator()
    generator.setFileName(str(target))
    generator.setSize(QSize(export_viewport.width, export_viewport.height))
    generator.setViewBox(QRect(0, 0, export_viewport.width, export_viewport.height))
    generator.setTitle("PyGeoLab export")
    generator.setDescription("Vector export generated by PyGeoLab")
    painter = QPainter(generator)
    try:
        Renderer().render(
            painter,
            document,
            export_viewport,
            palette,
            draw_background=not transparent,
        )
    finally:
        painter.end()
    return target
